[env:atom-lite]
platform = espressif32@^6.3.0
board = m5stack-atom
framework = arduino
board_build.partitions = partitions_4mb.csv
lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.1
    h2zero/NimBLE-Arduino@^1.4.3
build_flags = -DCORE_DEBUG_LEVEL=0

[env:esp32dev]
platform = espressif32@^6.3.0
board = esp32dev
framework = arduino
board_build.partitions = partitions_4mb.csv
lib_deps =
    adafruit/Adafruit NeoPixel@^1.15.1
    h2zero/NimBLE-Arduino@^1.4.3
build_flags = -DCORE_DEBUG_LEVEL=0 -DDEVKIT_LED
